### ISSUE TITLE
Batch norm问题

### ISSUE THREAD

**Issue by Pluto1314** [YimianDai/open-aff#15]
你好，最近我在使用pytorch进行复现，但是遇到一个问题。
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 64, 1, 1])

原因是因为经过GlobalAvgPooling后的特征图尺度都是C*1*1，这个1*1的特征图在BN就会报这个错误
您可以试试以下的代码，就可以复现我的问题了
import torch
a = torch.randn(1, 64, 1, 1)
bn = torch.nn.BatchNorm2d(64)
bn(a)

**Comment by Pluto1314** [comment]
你好，我重新试了一下，batch不为1的话就是可以的，打扰您了，，，

**Comment by roger-cv** [comment]
@Pluto1314 请问能分享一下您的pytorch版本的代码吗？谢谢

**Comment by yinyuhangi** [comment]
请问能分享一下您的pytorch版本的代码吗？ @Pluto1314

**Comment by bobo0810** [comment]
@roger-cv @yinyuhangi  希望能够帮到你们  https://github.com/bobo0810/AFF

**Comment by yinyuhangi** [comment]
感谢大佬 @bobo0810

**Comment by YimianDai** [comment]
谢谢 @bobo0810 ，代码已经 merge 了，在 ReadMe 中提及了您的贡献。

非常感谢~

**Comment by roger-cv** [comment]
@bobo0810 非常感谢您提供的pytorch的版本。
