### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by yinyuhangi** [YimianDai/open-aff#16]
您好，我想尝试把MS-CAM模块加入到其它网络模型中，请问加到backbone的最后，效果会怎么样呢？

**Comment by YimianDai** [comment]
我在语义分割实验里是加到 FPN 的跨层融合里的，也算 Backbone 的最后吧，效果可以的。

**Comment by yinyuhangi** [comment]
非常感谢您的回复，我试试看。

**Comment by yinyuhangi** [comment]
![image](https://user-images.githubusercontent.com/46810994/99531370-9472e100-29dd-11eb-9031-99a4a816dc62.png)
打扰您了，想问一下，如果把MS-CAM加入到yolov3中，插入到图中哪个位置效果可能比较好些呢？

**Comment by YimianDai** [comment]
我不是很熟悉 YOLO v3. 

AFF 的 Motivation 大致是用 Attention 来替换网络中原有的 Addition 和 Concat，这个 Addition 和 Concat 可以是分类网络 Backbone 里的，也可以是检测、分割网络（FPN、U-Net）里的跨层、多层融合之间的。

如果是我的话，我会先拿您给的截图中的跨层融合的 Concat 替换成 AFF。期待您的进一步反馈。
