### ISSUE TITLE
关于 Network visualization

### ISSUE THREAD

**Issue by hzlbbfrog** [YimianDai/open-aff#20]
作者您好，非常感谢您的工作！就是，那个我有一个很简单的问题，就是想问问您那个网络可视化咋做的呢？
  是提取最后的特征图，然后按照数字大小，绘制彩色云图然后调整透明度，覆盖到原图上面吗。
  还是别的思路呢。

**Comment by YimianDai** [comment]
@hzlbbfrog 在另一个 issue 里回答过了，简单复制一下，我是按照 https://mxnet.apache.org/versions/1.4.1/tutorials/vision/cnn_visualization.html 这个教程来得

基本的步骤就是：

1. 用 gradcam 里面的 运算符 conv /relu 构建一个跟你训练好的模型一模一样的网络，只是把标准的 conv /relu 替换成 gradcam 的 conv 和 relu
2. 将训练好的模型的权重赋予新的模型
3. 调用显示热力图的函数就可以了
