### ISSUE TITLE
Can you share inference time data for different AFF/iAFF models?

### ISSUE THREAD

**Issue by cmsflash** [YimianDai/open-aff#23]
Hi Yimian, I came here from your WACV 2021 presentation. This work looks pretty impressive.

As we discussed during your presentation, could you share the inference time data for different configurations (ResNet-50, -101, ResNeXt-50, etc.) as well as the numbers for baseline models and the hardware details? Thank you!

**Comment by YimianDai** [comment]
Hi, many thanks for your interest in our work.

We are preparing the journal version. On one hand, I will try to convert to PyTorch, which is requested by some github issues. One the other hand, I will upload these information and trained models once we finished the specific experiments. 

To be honest, current version is a bit rush to meet the graduation requirement of one EI-index conference paper... I will add more experiments on more tasks and deeper networks in the near future.

**Comment by cmsflash** [comment]
I see. Looking forward to the journal version. Please inform me when it's available. Thank you!
