### ISSUE TITLE
code implementation: multiplication of 2 in the final layer output

### ISSUE THREAD

**Issue by Crane-YU** [YimianDai/open-aff#3]
Hi @YimianDai , thanks for sharing your work and code. 
Just want to quick check the reason why you multiply 2 at the end of module block. 
Does it help you train the model or is it a normalization parameter?

**Comment by YimianDai** [comment]
I believe it has no impact on the training. The reason I use the multiplication of 2 is that I want to keep the total weights the same as addition. 

In the direct addition case, X + Y is actually 1 * X + 1 * Y, the sum of the weight is 2. However, in a soft selection way, M(X+Y) * X + (1 - M(X+Y)) * Y, the sum of the weight is 1, so I multiply 2 to keep them the same. Then the only difference between 1 * X + 1 * Y and M(X+Y) * X + (1 - M(X+Y)) * Y is the dynamic weight allocation, but the sum of the weights keeps the same.

**Comment by Crane-YU** [comment]
@YimianDai Thank you
